name: Continuous Integration
on:
  pull_request:
  push:
permissions: read-all

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    permissions: read-all
    strategy:
      fail-fast: false
      matrix:
        nodejs: ['14', '16']
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.nodejs }}
      - run: npm ci
      - name: Test
        run: npm run test
      - name: Lint
        run: npm run lint
